// <auto-generated />
using System;
using FieldOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815185101_AddOutboxFailedAt")]
    partial class AddOutboxFailedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldOps.Domain.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_email");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("FieldOps.Domain.Entities.Store", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("country_code");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_stores_country_code");

                    b.ToTable("stores", null, t =>
                        {
                            t.HasCheckConstraint("ck_stores_latitude_range", "\"latitude\" >= -90 AND \"latitude\" <= 90");

                            t.HasCheckConstraint("ck_stores_longitude_range", "\"longitude\" >= -180 AND \"longitude\" <= 180");
                        });
                });

            modelBuilder.Entity("FieldOps.Domain.Entities.Visit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_date");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("start_latitude");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("start_longitude");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "CompletedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_visits_completed_employee_completed_at")
                        .HasFilter("\"status\" = 'Completed'");

                    b.HasIndex("EmployeeId", "PlannedDate", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_visits_employee_planned_date");

                    b.HasIndex("EmployeeId", "StoreId", "PlannedDate")
                        .IsUnique()
                        .HasDatabaseName("ux_visits_active_employee_store_planned_date")
                        .HasFilter("\"status\" IN ('Planned', 'InProgress')");

                    b.HasIndex("StoreId", "PlannedDate", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_visits_store_planned_date");

                    b.ToTable("visits", null, t =>
                        {
                            t.HasCheckConstraint("ck_visits_start_coordinates_pair", "(\"start_latitude\" IS NULL AND \"start_longitude\" IS NULL) OR (\"start_latitude\" IS NOT NULL AND \"start_longitude\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_visits_start_latitude_range", "\"start_latitude\" IS NULL OR (\"start_latitude\" >= -90 AND \"start_latitude\" <= 90)");

                            t.HasCheckConstraint("ck_visits_start_longitude_range", "\"start_longitude\" IS NULL OR (\"start_longitude\" >= -180 AND \"start_longitude\" <= 180)");
                        });
                });

            modelBuilder.Entity("FieldOps.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptAt", "Id")
                        .HasDatabaseName("ix_outbox_messages_pending_next_attempt")
                        .HasFilter("\"processed_at\" IS NULL AND \"failed_at\" IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("FieldOps.Domain.Entities.Visit", b =>
                {
                    b.HasOne("FieldOps.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FieldOps.Domain.Entities.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
